# Generated by Django 4.1.5 on 2023-01-10 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GroceryLists',
            fields=[
                ('list_id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='MyList', max_length=50, verbose_name='List title')),
                ('note', models.CharField(default='', max_length=250, verbose_name='Note for list')),
                ('creation_date', models.DateField(verbose_name='Date of list creation')),
                ('red_date', models.DateField(verbose_name='Date of the planned shopping')),
            ],
        ),
    ]
